### ISSUE TITLE
compatible with ARTY-Z7

### ISSUE THREAD

**Issue by zenon4689** [semisgdh/SGDH-RVSoC#1]
Is it compatible with ARTY-Z7? 
I know that I have to create a new xpr file to apply it to the board, but I'm asking is it similar to making it.

**Comment by matbi86** [comment]
Hi @zenon4689 ,
We do not have plan to reflect in ARTY-Z7 not yet.
As you know, we are not supporting Zynq Chip set now.
However utilization is enough for porting into ARTY-Z7 I think.
Thanks
